# Default state for all rules
default: true
# Line length
MD013:
  code_blocks: false
# Inline HTML
MD033:
  allowed_elements: ["img", "p"]
# First line in a file should be a top-level heading
MD041: false