name: Heart
author: Bastien Gatellier
description: Analyze URLs using Heart
inputs:
  analysisService:
    description: Service name that analyze the URL (e.g. greenit)
    required: true
    default: ''
  file:
    description: Path to the JSON configuration file
    required: false
    default: ''
  inline:
    description: Inlined JSON configuration definition
    required: false
    default: ''
  threshold:
    description: A threshold between 0 and 100 that you want to reach with the analysis
    required: false
    default: ''
  listenerServices:
    description: Services names that process the result of the analyze, separated by commas (e.g. slack,bigquery)
    required: false
    default: ''
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.analysisService }}
    - ${{ github.GITHUB_WORKSPACE }}${{ inputs.file }}
    - ${{ inputs.inline }}
    - ${{ inputs.threshold }}
    - ${{ inputs.listenerServices }}
