name: Heart (webpages evaluation)
author: Bastien Gatellier
description: Evaluate webpages (GreenIT, performances, security) using Heart
branding:
  icon: heart
  color: purple
inputs:
  analysis_service:
    description: |
      Service name that analyze the URL.
      Available values: greenit, lighthouse, observatory, ssllabs-server
    required: true
    default: ''
  config:
    description: Configuration used by the analysis service. File path to a JSON file or JSON-inlined string.
    required: false
    default: ''
  threshold:
    description: Check if the score of the result reaches the given threshold (between 0 and 100).
    required: false
    default: ''
  except_listeners:
    description: |
      Comma-separated list of listener services that will not be triggered once the analysis is done. 
      Available values: bigquery, slack
    required: false
    default: ''
  only_listeners:
    description: |
      Comma-separated list of listener services that will be triggered once the analysis is done.
      Available values: bigquery, slack
    required: false
    default: ''
  google_application_credentials:
    description: Google Service account
    required: false
    default: ''
  observatory_api_url:
    description: Location of the Observatory API
    required: false
    default: ''
  observatory_analyze_url:
    description: Location of the Observatory website that provides the results
    required: false
    default: ''
  slack_api_token:
    description: Slack API token
    required: false
    default: ''
  slack_channel_id:
    description: Slack channel where the analysis results will be send
    required: false
    default: ''
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.analysis_service }}
    - ${{ inputs.config }}
    - ${{ inputs.threshold }}
    - ${{ inputs.except_listeners }}
    - ${{ inputs.only_listeners }}
  env:
    GOOGLE_APPLICATION_CREDENTIALS: ${{ inputs.google_application_credentials }}
    OBSERVATORY_API_URL: ${{ inputs.observatory_api_url }}
    OBSERVATORY_ANALYZE_URL: ${{ inputs.observatory_analyze_url }}
    SLACK_API_TOKEN: ${{ inputs.slack_api_token }}
    SLACK_CHANNEL_ID: ${{ inputs.slack_channel_id }}
