name: Heart
author: Bastien Gatellier
description: Analyze URLs using Heart
inputs:
  analysisService:
    description: |
      Service name that analyze the URL.
      Available values: dareboost, greenit, lighthouse, observatory, ssllabs-server
    required: true
    default: ''
  file:
    description: Set the file path to the JSON configuration used by the analysis service.
    required: false
    default: ''
  inline:
    description: Set the inline string of the JSON configuration used by the analysis service.
    required: false
    default: ''
  threshold:
    description: Check if the score of the result reaches the given threshold (between 0 and 100).
    required: false
    default: ''
  listenerServices:
    description: |
      Services names that process the result of the analyze, separated by commas.
      Available values: bigquery, slack
    required: false
    default: ''
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.analysisService }}
    - ${{ github.GITHUB_WORKSPACE }}${{ inputs.file }}
    - ${{ inputs.inline }}
    - ${{ inputs.threshold }}
    - ${{ inputs.listenerServices }}
