name: Heart (webpages evaluation)
author: Bastien Gatellier
description: Evaluate webpages (GreenIT, performances, security) using Heart
branding:
  icon: heart
  color: purple
inputs:
  analysis_service:
    description: |
      Service name that analyze the URL.
      Available values: greenit, lighthouse, observatory, ssllabs-server.
    required: true
    default: ''
  config:
    description: Configuration used by the analysis service. File path to a JSON file or JSON-inlined string.
    required: true
    default: ''
  threshold:
    description: Check if the score of the result reaches the given threshold (between 0 and 100).
    required: false
    default: ''
  listener_services_except:
    description: |
      Comma-separated list (without spaces) of listener services that will not be triggered once the analysis is done.
      This parameter is mutually exclusive with the listener_services_only one.
      Available values: mysql, slack.
    required: false
    default: ''
  listener_services_only:
    description: |
      Comma-separated list (without spaces) of listener services that will be triggered once the analysis is done.
      This parameter is mutually exclusive with the listener_services_except one.
      Available values: mysql, slack
    required: false
    default: ''
  mysql_database_url:
    description: Location and credentials of your MySQL database, in a URL format.
    required: false
    default: ''
  observatory_api_url:
    description: Location of the Observatory API.
    required: false
    default: ''
  observatory_analyze_url:
    description: Location of the Observatory website to view the the results.
    required: false
    default: ''
  slack_api_token:
    description: Slack API token.
    required: false
    default: ''
  slack_channel_id:
    description: Slack channel where the analysis results will be send.
    required: false
    default: ''
  verbose:
    description: Displays debug information
    required: false
    default: ''
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.analysis_service }}
    - ${{ inputs.config }}
    - ${{ inputs.threshold }}
    - ${{ inputs.listener_services_except }}
    - ${{ inputs.listener_services_only }}
    - ${{ inputs.verbose }}
  env:
    HEART_MYSQL_DATABASE_URL: ${{ inputs.mysql_database_url }}
    HEART_OBSERVATORY_API_URL: ${{ inputs.observatory_api_url }}
    HEART_OBSERVATORY_ANALYZE_URL: ${{ inputs.observatory_analyze_url }}
    HEART_SLACK_API_TOKEN: ${{ inputs.slack_api_token }}
    HEART_SLACK_CHANNEL_ID: ${{ inputs.slack_channel_id }}
