name: 🧹 Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Lint codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0

      - name: Lint GitHub workflows
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
        shell: bash

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          config: .markdownlint.yaml
